# Generated by Django 5.2.8 on 2025-11-07 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('senha', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('cliente', 'Cliente'), ('fornecedor', 'Fornecedor'), ('Admin', 'Administrador')], max_length=20)),
                ('telefone', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('endereco', models.CharField(max_length=200)),
            ],
            bases=('usuarios.usuario',),
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='usuarios.usuario')),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('categoria', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            bases=('usuarios.usuario',),
        ),
    ]
